### ISSUE TITLE
Shoulder_pan_joint of the fetch robot can't reach the upper limit

### ISSUE THREAD

**Issue by STAY-Melody** [vikashplus/robohive#115] opened 2023-10-18 13:58 UTC
Hi! 

Thanks to the work of Robohive team!

Before working with the [fetch_reach_v0.xml](https://github.com/vikashplus/robohive/blob/ef6f2c3deb93555d779bb3f9af0b3c21414c6bc0/robohive/envs/arms/fetch/assets/fetch_reach_v0.xml), I found that the `shoulder_pan_joint` can only reach 1.04 instead of its upper limit of 1.6056.

Here is the PNG to illustrate this phenomenon:

![fetch](https://github.com/vikashplus/robohive/assets/72594017/1e85f2dd-392c-4dc6-97af-339f9308123e)

Is this caused by the Mujoco actuator of the `shoulder_pan_joint`?

**Comment by vikashplus** [comment] 2023-10-18 16:27
Thanks @STAY-Melody  for trying RoboHive. I was able to reproduce this at my end. It seems like the arms starts colliding with the back of the body. 
![image](https://github.com/vikashplus/robohive/assets/12837145/1f7e927a-ea70-43cc-b2a9-e449633dae48)
The reason seems to be that the convex hull (used for mesh collisions) is not a good approximation of the actual geometry. The fix should involve creating a better collision surface that avoids that issue. The fix shouldn't be hard, I will update once it is available in the `dev` branch for you to try.

**Comment by vikashplus** [comment] 2023-10-19 03:47
Fixed in e16059360032c300a7f6503b8b47ba7253070d6e

**Closed by vikashplus** 2023-10-19 03:47 UTC
Labels: bug, enhancement
